name: Build, Push Docker Container, and Apply Manifests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-apply:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest .

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.3'  # Specify your preferred version

      # Configure kubectl with kubeconfig
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      # Update the Deployment YAML with the new image (optional)
      - name: Update image in Deployment YAML
        run: |
          sed -i "s|your-registry/your-postgres-image:tag|ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest|" ./manifests/deployment.yaml

      # Apply Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./manifests/
