name: Build, Push Docker Container, and Apply Manifests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-apply:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest .

      # Step 4: Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      # Step 5: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.3'  # Replace with your desired kubectl version

      # Step 6: Configure kubectl with kubeconfig
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      # Step 7: Update the image in postgres-deployment.yaml
      - name: Update image in Deployment YAML
        run: |
          sed -i "s|your-registry/your-postgres-image:tag|ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest|" ./manifests/postgres-deployment.yaml

      # Optional Debug Step: Verify manifests directory
      - name: List files for debugging
        run: |
          ls -R ./manifests

      # Step 8: Apply Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./manifests/
